version: '3.3'
services:
  app:
    image: dutchandbold/laravel-docker:latest
    ports:
      - '80:80'
    restart: always
    volumes:
      - ../projects/:/web
    environment:
      DB_HOST: db
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:5.6
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'cleancrm'
      MYSQL_USER: 'cleancrm'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
volumes:
  mysql-data: